version: '3.8'

services:
  database:
    build:
      context: ./database                   # 数据库 Dockerfile 的上下文目录
      dockerfile: Dockerfile                 # 根据实际 Dockerfile 名称调整
    container_name: truemen_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql                # 持久化数据库数据
    ports:
      - "3306:3306"                           # 将 MySQL 端口映射到主机

  webserver:
    build:
      context: ./webserver                    # 根据 webserver 的 Dockerfile 位置调整
      dockerfile: Dockerfile                  # 根据实际 Dockerfile 名称调整
    container_name: truemen_webserver
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST:-truemen-mysql}:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-verto}?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8000:8000"                          # 将后端服务端口映射到主机
    depends_on:
      - database                              # 确保数据库先启动
    volumes:
      - ./logs:/app/logs

volumes:
  db_data:                                   # 用于持久化数据库数据
